publicDomain: wc2018.soccer
defaultCommunity: grand-est
eventName: World Cup 2018

googleReCaptchaEnabled : false
googleReCaptchaSecretKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

oAuth2CredentialsFolder: ./credentials

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  rootPath: /api/*
  connector:
    type: http
    port: 9000

database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: predictor

  # the password
  password: iAMs00perSecrEET

  # the JDBC URL
  url: jdbc:h2:./predictor

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
